name: crud
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  micro_core_result: ^0.2.2
  easy_mask: ^2.0.1
  flutter:
    sdk: flutter
  flutter_validator: ^0.1.0+2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  intl: ^0.18.1
  path_provider: ^2.1.1
  flutter_bloc: ^8.0.0
  get_it: ^7.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
